### ISSUE TITLE
BladeEdge  Quest 10584 - works but throws a lot of errors 

### ISSUE THREAD

**Issue by marrvin2** [BosslandGmbH/Honorbuddy-Profiles#14]
(This was an Alliance char)
got this in my log mutliple times:

DoWhen-4627b8(debug)] Executing UseMagnetoCollector hook
[UseItem-4627b8(warning) @line 324]: Attribute 'MobId' is not recognized by this behavior--ignoring it.
[DoWhen-4627b8(debug)] Stopped executing UseMagnetoCollector hook
[(debug)] Executing UseMagnetoCollector hook
[DoWhen-4627b8(debug)] Stopped executing UseMagnetoCollector hook
[DoWhen-4627b8(debug)] Executing UseMagnetoCollector hook
[UseItem-4627b8(warning) @line 324]: Attribute 'MobId' is not recognized by this behavior--ignoring it.
[(error)] For DoWhenActivity ActivityName(UseMagnetoCollector), predicate (() => Me.CurrentTarget != null && Me.CurrentTarget.Entry == 21729 && !Me.CurrentTarget.HasAura(37136)) was not reset by execution.
  This is a profile problem, and can result in erratic Honorbuddy behavior.
  The predicate must return to 'false' after the action has been successfully executed.
[UseItem-4627b8(warning) @line 324]: Attribute 'MobId' is not recognized by this behavior--ignoring it.

**Comment by EchoTiger** [comment]
Seems the DoWhen is looping too quickly before the CurrenTarget mob in question can despawn.
A simple  ClearTarget(); with a slight wait timer at the end of the DoWhen should fix it up.
