### ISSUE TITLE
Quest "Scratches" in Bladge Edge will not complete

### ISSUE THREAD

**Issue by marrvin2** [BosslandGmbH/Honorbuddy-Profiles#9]
This is the quest where you have to stand in a circle to summon a small bird that will follow you for 10 minutes (to reach quest turn in npc).
Currently the profile uses ground mount to get to turn in NPC - **but quest does not complete!**
**Reason:** About half the way the bird(buff) gets lost as the bird is to slow to catch up.
You actually have to  **RUN**  to Quest turn in !
Did  this by hand and it worked.

http://www.wowhead.com/quest=10556/scratches

-- marrvin

**Comment by marrvin2** [comment]
using the latest profile from today the bird(buff) still gets lost before entering town due to mounted char is ways to fast.
This leads to a total  "questing halt".
I saved the log in case you need it.

**Comment by EchoTiger** [comment]
I don't suppose you still have the log?
There should be a DoWhen hook in there that watches the bird position and 'stops' the bot if it gets too far away.

**Comment by marrvin2** [comment]
here is the last log:
[2800 2017-10-23 13.45 - Kopie.txt](https://github.com/BosslandGmbH/Honorbuddy-Profiles/files/1408196/2800.2017-10-23.13.45.-.Kopie.txt)

**Comment by marrvin2** [comment]
oh yes I noted that the char  "once" waited for the bird to come closer. But then it was moving mounted to the questgiver  without pausing, loosing the buff after half of the remaining way to quest turn in NPC
